In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go

In [2]:
mp_key = "5KTRCxoFyWvECvvRVCS0OeflSzkuO7df"
mp_id = "mp-7575"

In [3]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_bs = m.get_bandstructure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
    ph_bs = m.get_phonon_bandstructure_by_material_id(mp_id)
    ph_dos = m.get_phonon_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving PhononBSDOSDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [58]:
i_atom = 1
i_symmop = 3
print("Première opération de symétrie (symmorphique): rotation d'ordre 2 (x,y,z) -> (-x,-y,z)")
view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')
symmop = symmops[i_symmop - 1]
print(symmop)
pos_init = conv_struc.sites[i_atom -1].frac_coords
print("position initiale: ", pos_init)
pos_final = symmop.operate(pos_init)
print("position finale: ", pos_final)

Première opération de symétrie (symmorphique): rotation d'ordre 2 (x,y,z) -> (-x,-y,z)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
position initiale:  [0.75 0.25 0.25]
position finale:  [-0.75 -0.25  0.25]


In [59]:
i_atom = 2
i_symmop = 6
print("Deuxième opération de symétrie (symmorphique): réflexion par rapport à un plan miroir (x,y,z) -> (y,x,z)")
view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')
symmop = symmops[i_symmop - 1]
print(symmop)
pos_init = conv_struc.sites[i_atom -1].frac_coords
print("position initiale: ", pos_init)
pos_final = symmop.operate(pos_init)
print("position finale: ", pos_final)
print("Les positions initiales et finales sont confondues car elles se trouvent sur le plan miroir")

Deuxième opération de symétrie (symmorphique): réflexion par rapport à un plan miroir (x,y,z) -> (y,x,z)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

Rot:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
tau
[0. 0. 0.]
position initiale:  [0.75 0.75 0.75]
position finale:  [0.75 0.75 0.75]
Les positions initiales et finales sont confondues car elles se trouvent sur le plan miroir


In [60]:
i_atom = 3
i_symmop = 14
print("Troisième opération de symétrie (symmorphique): réflexion par rapport à un plan miroir (x,y,z) -> (z,y,x)")
view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')
symmop = symmops[i_symmop - 1]
print(symmop)
pos_init = conv_struc.sites[i_atom -1].frac_coords
print("position initiale: ", pos_init)
pos_final = symmop.operate(pos_init)
print("position finale: ", pos_final)


Troisième opération de symétrie (symmorphique): réflexion par rapport à un plan miroir (x,y,z) -> (z,y,x)


JsmolView(layout=Layout(align_self='stretch', height='400px'))

Rot:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
tau
[0. 0. 0.]
position initiale:  [0.25 0.25 0.75]
position finale:  [0.75 0.25 0.25]
